QINIU_AK: MIAMLgAOmGfbRNxVz0TtzyJ93508b42ShZeE40s
QINIU_SK: SsQT2tLHiskrsIZWLcPxiZxiSWU6i499_jljoUla
QINIU_BUCKET: cassiuschen-photo
QINIU_DOMAIN: 7xi7oz.com1.z0.glb.clouddn.com
DB_HOST: 10.10.72.139:27017
DB_NAME: cY3NadTDFhuiRX6f
RAILS_ENV: docker
REDIS_HOST: 10.10.71.37
REDIS_PASSWORD: tUA3hFXsqv
REDIS_PORT: 49616
DB_PASSWORD: pw2uNtS018nx9CYLM
DB_USERNAME: uPT2mDfEpC7tUxrv
